#!/usr/bin/env bash

#
# Constants
#
PROGNAME=$(basename "$0")

SCRIPT_VERSION="0.0.2"
DEFAULT_MESSAGE="Go go go!"

CONFIG_DIR="$HOME/.config/ttl"
CONFIG_FILE="$CONFIG_DIR/ttl.conf"

USAGE="usage: $PROGNAME [--time time] [--message message]
$PROGNAME calculates time to leave

options:
  -h, --help              display this help and exit
  -l, --long              display full time
  -m, --message message   set leave message. Default $DEFAULT_MESSAGE
  -t, --time time         set leave hour in HH:MM format
      --version           display version info and exit
"

EXIT_SUCCESS=0
EXIT_ERROR=1

#
# Helpers
#
print_std_err() {
  echo "$PROGNAME: $*" >&2
}

print_std_out() {
  echo "$*"
}

validate_second_option() {
  if [[ -z "$1" || "$1" == -* ]]; then
    print_std_err "$2"
    exit $EXIT_ERROR
  fi
}

write_configuration() {
  mkdir -p "$CONFIG_DIR"
  {
    echo "LEAVE_TIME=\"$user_leave_time\""
    echo "MESSAGE=\"$user_message\""
  } > "$CONFIG_FILE"
}

prompt_for_leave_time() {
  local input_time
  while true; do
    read -rp "set leave time (HH:MM): " input_time
    if [[ "$input_time" =~ ^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$ ]]; then
      user_leave_time="$input_time"
      break
    else
      print_std_err "wrong format"
    fi
  done
}

# Variables
is_long_time=false
has_config_changed=false
cli_leave_time=""
cli_message=""
user_leave_time=""
user_message=""

main() {
  # Parse options
  while test $# -ne 0; do
    case $1 in
      -h|--help)
        print_std_out "$USAGE";
        exit $EXIT_SUCCESS;;
      -l|--long)
        is_long_time=true
        shift
        continue;;
      -m|--message)
        validate_second_option "$2" "message requires a value"
        cli_message=$2
        has_config_changed=true
        shift
        shift
        continue;;
      -t|--time)
        validate_second_option "$2" "time requires a value"
        if [[ ! "$2" =~ ^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$ ]]; then
          print_std_err "invalid time format: $2 expected: HH:MM"
          exit $EXIT_ERROR
        fi
        cli_leave_time=$2
        has_config_changed=true
        shift
        shift
        continue;;
      --version)
        print_std_out "$SCRIPT_VERSION";
        exit $EXIT_SUCCESS;;
      -*)
        print_std_err "invalid option: $1"
        exit $EXIT_ERROR;;
      *)
        print_std_err "invalid option: $1"
        exit $EXIT_ERROR;;
    esac
  done

  # Load configuration file if exists
  if [[ -f "$CONFIG_FILE" ]]; then
    source "$CONFIG_FILE"
    user_leave_time=$LEAVE_TIME
    user_message=$MESSAGE
  else
    user_message=$DEFAULT_MESSAGE
    has_config_changed=true
  fi

  [[ -n "$cli_leave_time" ]] && user_leave_time="$cli_leave_time"
  [[ -n "$cli_message" ]] && user_message="$cli_message"
  
  # If still no leave time (not found in configuration and not provided with -t), prompt
  if [[ -z "$user_leave_time" ]]; then
    prompt_for_leave_time
  fi

  if $has_config_changed; then
    write_configuration
  fi

  # Start logic
  current_seconds=$(( 10#$(date +%H)*3600 + 10#$(date +%M)*60 + 10#$(date +%S)))

  leave_hour=${user_leave_time%%:*}
  leave_mins=${user_leave_time##*:}
  leave_secs=$((10#$leave_hour*3600 + 10#$leave_mins*60))

  diff=$((leave_secs - current_seconds))

  if ((diff < 0)); then
    print_std_out "$user_message"
  else
    # Calculate hours and minutes
    hours=$((diff / 3600))
    minutes=$(((diff % 3600) / 60))

    # Format hours and minutes to two digits
    if (($hours < 10)); then
      hours="0${hours}"
    fi

    if (($minutes < 10)); then
      minutes="0${minutes}"
    fi

    # Print remaining time
    if $is_long_time; then
      print_std_out "You have ${hours}h ${minutes}m"
    else
      print_std_out "${hours}:${minutes}"
    fi
  fi

  exit $EXIT_SUCCESS
}

main "$@"